### ISSUE TITLE
implementation-strategy.md translation suggestion

### ISSUE THREAD

**Issue by Lukse** [aleksas/foundation#4]
Organizacija ir ištrinkite savo organizacijos tranzakcijas -> Organizacija ir ištrinkite savo organizacijos transakcijas

**Comment by Lukse** [comment]
Jei jums reikia pagalbos, galite įsigyti palikymą -> Jei jums reikia pagalbos, galite įsigyti palaikymą

**Comment by aleksas** [comment]
fix https://github.com/aleksas/foundation/commit/c48b7a2f1809e38d658caef3ee228fb223c6fa44
